// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvwpsqdyscbjdhvprgyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2d3BzcWR5c2NiamRodnByZ3lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTk4NjUsImV4cCI6MjA1ODIzNTg2NX0.SuAzVDGq1MYWhPiSU8ReyTscbGZ8iJ2Dkr0dDe1cXxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);