
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvwpsqdyscbjdhvprgyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2d3BzcWR5c2NiamRodnByZ3lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTk4NjUsImV4cCI6MjA1ODIzNTg2NX0.SuAzVDGq1MYWhPiSU8ReyTscbGZ8iJ2Dkr0dDe1cXxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Ensure we have a comment_likes table
const createCommentLikesTableIfNotExists = async () => {
  try {
    const { error } = await supabase.rpc('create_comment_likes_if_not_exists');
    if (error) console.error('Error creating comment_likes table:', error);
  } catch (error) {
    console.error('Failed to create comment_likes table:', error);
  }
};

// Ensure we have a notifications table
const createNotificationsTableIfNotExists = async () => {
  try {
    const { error } = await supabase.rpc('create_notifications_if_not_exists');
    if (error) console.error('Error creating notifications table:', error);
  } catch (error) {
    console.error('Failed to create notifications table:', error);
  }
};

// Initialize required tables
createCommentLikesTableIfNotExists();
createNotificationsTableIfNotExists();
